version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: grocery
      POSTGRES_PASSWORD: grocerypass
      POSTGRES_DB: grocery_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
